#This file should be in the same directory where example.py is in
prefix = "."
stop-words = "stopwords.txt"

dataset = "parsed_docs"
corpus = "file.toml"
index = "idx"

# specify a better filter later

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
